liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    # define your filter sets under this option
    filter_sets:

        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_thumbnail:

            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [375, 375]
                    mode:          inset
                    allow_upscale: true

                # create border by placing image on larger black background
                background:
                    size:           [376, 376]
                    position:       center
                    color:          '#fff'

        search_thumbnail:
            jpeg_quality:           85
            png_compression_level:  8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:           [50,50]
                    mode:           inset
                    allow_upscale:  true
                background:
                    size:           [53,53]
                    position:       center
                    color:          '#fff'

        equipment_thumbnail:
            jpeg_quality:           95
            png_compression_level:  10
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:           [798,798]
                    mode:           inset
                    allow_upscale:  true
                background:
                    size:           [800,800]
                    position:       center
                    color:          '#fff'

        news_thumbnail:
            jpeg_quality:           95
            png_compression_level:  10
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:           [376,376]
                    mode:           inset
                    allow_upscale:  true
                background:
                    size:           [377,377]
                    position:       center
                    color:          '#272727'

        partners_logo:
            jpeg_quality:           95
            png_compression_level:  10
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:           [116,24]
                    mode:           inset
                    allow_upscale:  true
                background:
                    size:           [116,24]
                    position:       center
                    color:          '#272727'