vich_uploader:
    db_driver: orm

    mappings:
        services_images:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'

        service_logo_images:
            uri_prefix: /images/services/logo
            upload_destination: '%kernel.project_dir%/public/images/services/logo'

        product_images:
            uri_prefix: /images/product
            upload_destination: '%kernel.project_dir%/public/images/product'

        product_images_top:
            uri_prefix: /images/product/top
            upload_destination: '%kernel.project_dir%/public/images/product/top'

        portfolio_images:
            uri_prefix: /images/portfolio
            upload_destination: '%kernel.project_dir%/public/images/portfolio'

        category_images:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'

        translations:
            uri_prefix: /translations
            upload_destination: '%kernel.project_dir%/translations'

        about_images:
            uri_prefix: /images/about
            upload_destination: '%kernel.project_dir%/public/images/about'

        partners_images:
            uri_prefix: /images/partners
            upload_destination: '%kernel.project_dir%/public/images/partners'

        partners_logo_images:
            uri_prefix: /images/partners/logo
            upload_destination: '%kernel.project_dir%/public/images/partners/logo'

        home_page_images_1:
            uri_prefix: /images/home/1
            upload_destination: '%kernel.project_dir%/public/images/home/1'

        home_page_images_2:
            uri_prefix: /images/home/2
            upload_destination: '%kernel.project_dir%/public/images/home/2'

        home_page_images_comment:
            uri_prefix: /images/home/comment
            upload_destination: '%kernel.project_dir%/public/images/home/comment'