vich_uploader:
    db_driver: orm

    mappings:
        services_images:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'

        product_images:
            uri_prefix: /images/product
            upload_destination: '%kernel.project_dir%/public/images/product'

        product_images_top:
            uri_prefix: /images/product/top
            upload_destination: '%kernel.project_dir%/public/images/product/top'

        portfolio_images:
            uri_prefix: /images/portfolio
            upload_destination: '%kernel.project_dir%/public/images/portfolio'

        category_images:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'