vich_uploader:
    db_driver: orm

    mappings:
        services_images:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'

        machines_images:
            uri_prefix: /images/machines
            upload_destination: '%kernel.project_dir%/public/images/machines'

        portfolio_images:
            uri_prefix: /images/portfolio
            upload_destination: '%kernel.project_dir%/public/images/portfolio'

        category_images:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'