# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'ua'
    fromEmail: noreply@myshop.ua
    fromName: MyShop
    adminEmail: admin@myshop.ua

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        # uncomment the next line if you are not using autoconfigure
        # tags: [kernel.event_subscriber]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Admin\ProductsAdmin:
        arguments: [~,App\Entity\Products,~, '@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin,group: Основной контент, manager_type: orm, label: Товары}

    App\Admin\CategoryAdmin:
        arguments: [~,App\Entity\Categories,~ ]
        tags:
            - { name: sonata.admin,group: Основной контент, manager_type: orm, label: Категории}

    App\Admin\CategoryTranslationsAdmin:
        arguments: [~,App\Entity\CategoriesTranslations,~,'@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin,group: Переводы, manager_type: orm, label: Переводы Категорий}

    App\Admin\ProductImagesAdmin:
        arguments: [~,App\Entity\ProductImages,~, '@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    App\Admin\ProductsTranslationsAdmin:
        arguments: [~,App\Entity\ProductsTranslations,~,'@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin,group: Переводы, manager_type: orm, label: Переводы товаров}

    App\Admin\ContactAdmin:
        arguments: [~,App\Entity\Contacts,~ ]
        tags:
            - { name: sonata.admin,group: Контакты, manager_type: orm, label: Контакты}

    App\Admin\TranslationsAdmin:
        arguments: [~, App\Entity\StaticTranslations,~]
        tags:
            - { name: sonata.admin,group: Переводы, manager_type: orm, label: Статические переводы}

    App\Admin\AboutAdmin:
        arguments: [~,App\Entity\About,~]
        tags:
            - { name: sonata.admin,group: Контакты, manager_type: orm, label: О нас}

    App\Admin\ServiceAdmin:
        arguments: [~,App\Entity\Services,~, '@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin,group: Основной контент, manager_type: orm, label: Услуги}

    App\Admin\ServiceTranslationAdmin:
        arguments: [~,App\Entity\ServiceTranslations,~,'@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin,group: Переводы, manager_type: orm, label: Переводы услуг}

    App\Admin\ServiceImagesAdmin:
        arguments: [~,App\Entity\ServiceImages,~, '@liip_imagine.cache.manager' ]
        tags:
            - { name: sonata.admin,  manager_type: orm, show_in_dashboard: false}

    App\Admin\CommentsAdmin:
        arguments: [~,App\Entity\Comments,~]
        tags:
            - { name: sonata.admin,group: Коментарии и отзывы, manager_type: orm, label: Коментарии на главной}

    App\Admin\FeedbackAdmin:
        arguments: [~,App\Entity\Feedback,~]
        tags:
            - { name: sonata.admin,group: Коментарии и отзывы, manager_type: orm, label: Форма обратной связи}